LABORATORIO 2

Instalando y cargando los paquetes


```{r}
install.packages("nycflights13")

library(tidyverse)
library(dplyr)
library(ggplot2)
library(nycflights13)

view(flights)
view(airports)
view(planes)
view(airlines)
view(weather)

```

---1) Inner-join

```{r}
# 1.1
flights %>%
  inner_join(planes, by="tailnum")
# 1.2  
flights %>%
  inner_join(airlines, by="carrier")
# 1.3
flights %>%
  inner_join(airports, by=c("origin" = "faa")) %>%
  inner_join(airports, by=c("dest" = "faa"))

# 1.4
flights %>%
  inner_join(weather, by=c("year", "month", "day", "hour", "origin"))         
               
```

---2) Data manipulation

2.1
```{r}
flights %>%
  count(year, month, day) %>%
  filter(n > 1000) %>%
  arrange(desc(n))

```

2.2

```{r}
flight_selected <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)

flight_selected

```

2.3

```{r}
airlines %>%
  left_join(flight_selected, by="carrier") %>%
  select(-origin, -dest) %>%
  mutate(tot_delay = arr_delay + dep_delay) 
```

2.4

```{r}
precip_delay <- flights %>%
  inner_join(weather, by=c("year", "month", "day", "hour", "origin")) %>%
  group_by(precip) %>%
  summarize(delay=mean(dep_delay, na.rm=TRUE)) %>%
  replace_na(list(delay=0))

precip_delay

```

2.5

```{r}
ggplot(precip_delay, aes(x=precip, y=delay)) +
  geom_point()
```
2.6

```{r}
flights_airports <- flights %>%
  filter(year == 2013, month == 5, day == 10) %>%
  group_by(dest) %>%
  summarize(delay=mean(arr_delay, na.rm=TRUE)) %>%
  inner_join(airports, by=c("dest"="faa"))
  
flights_airports

```
2.7

```{r}
ggplot(flights_airports, aes(x=lon, y=lat, color=delay, size=delay)) +
  geom_point()
```

2.8 

```{r}
flights %>%
  inner_join(planes, by="tailnum", suffix=c("_flights", "_planes")) %>%
  transmute(tailnum, manufacturer, pi = (dep_delay + arr_delay)/air_time)
```


